spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
    connection-test-query: SELECT 1
    validation-query: SELECT 1
  jpa:
    database: mysql
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    properties.mail.smtp:
      auth: true
      starttls:
        enable: true
        required: true
logging:
  level:
    root: warn
    kr.lul.kobalttown: info
