kobalttown.lul.kr:
  resource:
    css.location: [kobalttown-design]/public/css/
    js.location: [kobalttown-design]/public/js/
  email:
    account-activate-code:
      address: dev@lul.kr
      name: "개발 테스트 메일"
      subject: "계정 활성화 코드입니다."
      template: "_email/account-activate"
      host: "http://localhost:8080"
spring:
  thymeleaf:
    cache: false
    prefix: file:./templates/
  datasource:
    url: jdbc:mysql://localhost/kobalttown
    max-active: 1
    username: root
    password: "[ --- PASSWORD --- ]"
  jpa:
    generate-ddl: true
    show-sql: true
  mail:
    username: "just.burrow@lul.kr"
    password: "[ --- PASSWORD --- ]"
logging:
  level:
    root: warn
    kr.lul.kobalttown: debug
