kobalttown.lul.kr:
  resource:
    # css.location : [kobalttown-design]/public/css/
    css.location: file:./templates/css/
    # css.location : [kobalttown-design]/public/js/
    js.location: file:./templates/js/
spring:
  thymeleaf:
    cache: false
    prefix: file:./templates/
logging:
  level:
    root: warn
    kr.lul.kobalttown: trace
